/**
 * Hand-authored pixel art. Each sprite is a list of equal-length rows mapped
 * through PALETTE. No external assets, so nothing to license or load.
 * `pnpm validate:sprites` checks every row length and character.
 */

export const PALETTE: Record<string, string | null> = {
    '.': null,
    k: '#1d1710',
    K: '#332618',
    G: '#3f7a2e',
    g: '#5fa83c',
    h: '#8ed15a',
    T: '#6b4a2a',
    t: '#8a6238',
    W: '#f7efe0',
    S: '#cdbb9c',
    s: '#9b8a70',
    A: '#BFFF00',
    a: '#7fae00',
    Y: '#f2c14e',
    R: '#d1452f',
    P: '#c46bb0',
    B: '#4f7fb8',
    b: '#7fb0dd',
    O: '#e08a3c',
    F: '#ddd8c8',
    M: '#c46bb0',
}

export type Sprite = string[]

/* ---------- characters ---------- */

export const HERO_A: Sprite = [
    '................',
    '.......AA.......',
    '......AAAA......',
    '.....AAAAAA.....',
    '....AAAAAAAA....',
    '...AAAAAAAAAA...',
    '..KKKKKKKKKKKK..',
    '....KWWWWWWK....',
    '....KWkWWkWK....',
    '....KWWWWWWK....',
    '.....KWWWWK.....',
    '...KKBBBBBBKK...',
    '..KBBBBBBBBBBK..',
    '..KBBBBBBBBBBK..',
    '...KBBBBBBBBK...',
    '....KKK..KKK....',
]

export const HERO_B: Sprite = [
    '................',
    '.......AA.......',
    '......AAAA......',
    '.....AAAAAA.....',
    '....AAAAAAAA....',
    '...AAAAAAAAAA...',
    '..KKKKKKKKKKKK..',
    '....KWWWWWWK....',
    '....KWkWWkWK....',
    '....KWWWWWWK....',
    '.....KWWWWK.....',
    '...KKBBBBBBKK...',
    '..KBBBBBBBBBBK..',
    '..KBBBBBBBBBBK..',
    '..KBBBBBBBBBBK..',
    '..KKK......KKK..',
]

export const VILLAGER_A: Sprite = [
    '................',
    '.....KKKKKK.....',
    '....KYYYYYYK....',
    '....KYYYYYYK....',
    '....KWWWWWWK....',
    '....KWkWWkWK....',
    '.....KWWWWK.....',
    '...KKKOOOOKKK...',
    '..KOOOOOOOOOOK..',
    '..KOOOOOOOOOOK..',
    '..KWOOOOOOOOWK..',
    '..KKOOOOOOOOKK..',
    '...KOOOOOOOOK...',
    '....KTTKKTTK....',
    '....KTTK.KTTK...',
    '....KKK...KKK...',
]

export const VILLAGER_B: Sprite = [
    '................',
    '................',
    '.....KKKKKK.....',
    '....KYYYYYYK....',
    '....KYYYYYYK....',
    '....KWWWWWWK....',
    '....KWkWWkWK....',
    '.....KWWWWK.....',
    '...KKKOOOOKKK...',
    '..KOOOOOOOOOOK..',
    '..KOOOOOOOOOOK..',
    '..KWOOOOOOOOWK..',
    '..KKOOOOOOOOKK..',
    '...KOOOOOOOOK...',
    '....KTTKKTTK....',
    '....KKK...KKK...',
]

/* ---------- the four spirits of the ritual ---------- */

/** Delve digs scrolls out of the archive. */
export const DELVE: Sprite = [
    '................',
    '.....KKKKKK.....',
    '....KTTTTTTK....',
    '...KTTTTTTTTK...',
    '...KTkTTTTkTK...',
    '...KTTTWWTTTK...',
    '....KTTTTTTK....',
    '...KKTTTTTTKK...',
    '..KTTTTTTTTTTK..',
    '..KTWWWWWWWWTK..',
    '..KTWSSSSSSWTK..',
    '..KTWWWWWWWWTK..',
    '...KTTTTTTTTK...',
    '....KttKKttK....',
    '.....KK..KK.....',
    '................',
]

export const DELVE_SICK: Sprite = [
    '................',
    '.....KKKKKK.....',
    '....KTTTTTTK....',
    '...KTTTTTTTTK...',
    '...KTRTTTTRTK...',
    '...KTTTRRTTTK...',
    '....KTTTTTTK....',
    '...KKTTTTTTKK...',
    '..KTTTTTTTTTTK..',
    '..KTWWRRRRWWTK..',
    '..KTWRSSSSRWTK..',
    '..KTWWRRRRWWTK..',
    '...KTTTTTTTTK...',
    '....KttKKttK....',
    '.....KK..KK.....',
    '................',
]

/** Muse decides which rite to use. A drifting wisp with one eye. */
export const MUSE: Sprite = [
    '.......AA.......',
    '......AaaA......',
    '.....AaaaaA.....',
    '....AaaWWaaA....',
    '....AaWkkWaA....',
    '....AaaWWaaA....',
    '.....AaaaaA.....',
    '......AaaA......',
    '.......AA.......',
    '................',
    '......aaaa......',
    '.......aa.......',
    '................',
    '.......aa.......',
    '................',
    '................',
]

export const MUSE_SICK: Sprite = [
    '.......RR.......',
    '......RssR......',
    '.....RssssR.....',
    '....RssWWssR....',
    '....RsWkkWsR....',
    '....RssWWssR....',
    '.....RssssR.....',
    '......RssR......',
    '.......RR.......',
    '................',
    '......ssss......',
    '.......ss.......',
    '................',
    '.......ss.......',
    '................',
    '................',
]

/** Errand runs out into the world and brings a fact back. */
export const ERRAND: Sprite = [
    '................',
    '....KKKKKKKK....',
    '...KSSSSSSSSK...',
    '...KSAKSSKASK...',
    '...KSSSSSSSSK...',
    '...KSSKKKKSSK...',
    '....KSSSSSSK....',
    '..KKKSSSSSSKKK..',
    '.KSSSSSSSSSSSSK.',
    '.KSSSSSSSSSSSSK.',
    '.KSSKSSSSSSKSSK.',
    '..KKKSSSSSSKKK..',
    '....KSSKKSSK....',
    '....KSSK.KSSK...',
    '....KKK...KKK...',
    '................',
]

export const ERRAND_SICK: Sprite = [
    '................',
    '....KKKKKKKK....',
    '...KsssssssK....',
    '...KsRKssKRsK...',
    '...KsssssssKK...',
    '...KssKKKKssK...',
    '....KsRRRRsK....',
    '..KKKssRRssKKK..',
    '.KssssRRRRssssK.',
    '.KsssRRssRRsssK.',
    '.KssKsssssKsssK.',
    '..KKKsssssKKKK..',
    '....KssKKssK....',
    '.....KK...KK....',
    '................',
    '................',
]

/** Echo speaks the answer aloud. A mask on a stand. */
export const ECHO: Sprite = [
    '................',
    '....KKKKKKKK....',
    '...KWWWWWWWWK...',
    '..KWWAAWWAAWWK..',
    '..KWWAAWWAAWWK..',
    '..KWWWWWWWWWWK..',
    '..KWWWAAAAWWWK..',
    '..KWWAAAAAAWWK..',
    '...KWWAAAAWWK...',
    '....KWWWWWWK....',
    '.....KKKKKK.....',
    '.......SS.......',
    '.......SS.......',
    '.....KSSSSK.....',
    '....KSSSSSSK....',
    '....KKKKKKKK....',
]

export const ECHO_SICK: Sprite = [
    '................',
    '....KKKKKKKK....',
    '...KWWWWWWWWK...',
    '..KWWRRWWRRWWK..',
    '..KWWRRWWRRWWK..',
    '..KWWWWWWWWWWK..',
    '..KWWWRRRRWWWK..',
    '..KWWRRRRRRWWK..',
    '...KWWRRRRWWK...',
    '....KWWWWWWK....',
    '.....KKKKKK.....',
    '.......SS.......',
    '.......SS.......',
    '.....KSSSSK.....',
    '....KSSSSSSK....',
    '....KKKKKKKK....',
]

/** What a spirit looks like before you carry the Lantern. */
export const FOG_A: Sprite = [
    '................',
    '.....FFFFF......',
    '...FFFFFFFFF....',
    '..FFFFFFFFFFF...',
    '.FFFFFFFFFFFFF..',
    '.FFFFFFFFFFFFF..',
    'FFFFFFFFFFFFFFF.',
    'FFFFFFFFFFFFFFF.',
    'FFFFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFF..',
    '.FFFFFFFFFFFFF..',
    '..FFFFFFFFFFF...',
    '...FFFFFFFFF....',
    '.....FFFFF......',
    '................',
    '................',
]

export const FOG_B: Sprite = [
    '................',
    '......FFFFF.....',
    '....FFFFFFFFF...',
    '...FFFFFFFFFFF..',
    '..FFFFFFFFFFFFF.',
    '..FFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFFFF',
    '.FFFFFFFFFFFFFFF',
    '.FFFFFFFFFFFFFFF',
    '..FFFFFFFFFFFFF.',
    '..FFFFFFFFFFFFF.',
    '...FFFFFFFFFFF..',
    '....FFFFFFFFF...',
    '......FFFFF.....',
    '................',
    '................',
]

/** The standing stone you ask the Oracle from. */
export const PLINTH: Sprite = [
    '................',
    '.......AA.......',
    '......AAAA......',
    '.......AA.......',
    '................',
    '.....KSSSSK.....',
    '....KSSSSSSK....',
    '....KSSAASSK....',
    '....KSSAASSK....',
    '....KSSSSSSK....',
    '....KSSSSSSK....',
    '....KSsSSsSK....',
    '....KSSSSSSK....',
    '...KSSSSSSSSK...',
    '...KSSSSSSSSK...',
    '..KSSSSSSSSSSK..',
    '..KssssssssssK..',
    '..KKKKKKKKKKKK..',
]

/* ---------- scenery ---------- */

export const TREE: Sprite = [
    '.....GGGGG......',
    '...GGhhhhhGG....',
    '..GhhhhhhhhhG...',
    '.GhhhhhhhhhhhG..',
    '.GhhhghhhghhhG..',
    'GhhhhhhhhhhhhhG.',
    'GhhhghhhhhghhhG.',
    '.GhhhhhhhhhhhG..',
    '..GhhhhhhhhhG...',
    '...GGhhhhhGG....',
    '.....GGGGG......',
    '......TTt.......',
    '......TTt.......',
    '......TTt.......',
    '.....TTTtt......',
    '....TTTTttt.....',
]

export const BUSH: Sprite = [
    '................',
    '................',
    '................',
    '................',
    '......GGGG......',
    '....GGgggGG.....',
    '...GgghhhggG....',
    '..GgghhhhhggG...',
    '..GghhMhhhMhG...',
    '..GgghhhhhhgG...',
    '..KGgggggggGK...',
    '...KGGGGGGGK....',
    '....KKKKKKK.....',
    '................',
    '................',
    '................',
]

export const FLOWERS: Sprite = [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..M....Y........',
    '.MMM..YYY...M...',
    '..M....Y...MMM..',
    '..g....g....M...',
    '..g....g....g...',
    '.ggg..ggg..ggg..',
    '................',
    '................',
    '................',
]

export const MUSHROOMS: Sprite = [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...RRR..........',
    '..RRWRR....RR...',
    '..RRRRR...RRWR..',
    '...WWW....RRRR..',
    '...WWW.....WW...',
    '...........WW...',
    '................',
    '................',
]

export const ROCK: Sprite = [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....KKKKK......',
    '...KKSSSSSKK....',
    '..KSSSSSSSSSK...',
    '..KSSSSSSSSSK...',
    '..KsssssssssK...',
    '..KKKKKKKKKKK...',
    '................',
    '................',
]

/** Grows as Delve drags more of the archive into the circle. */
export const SCROLLS: Sprite = [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..KWWK..KWWK....',
    '..KWSK..KWSK....',
    '..KWWK..KWWK....',
    '.KWWWWKKWWWWK...',
    '.KWSSSWWSSSWK...',
    '.KWWWWWWWWWWK...',
    '..KKKKKKKKKK....',
    '................',
]
