/**
 * Generated by scripts/gen-sprites.py. Do not hand-edit.
 *
 * The scenery is generated so its shading stays consistent, and the townsfolk
 * are one hand-drawn body recoloured per person, so the town reads as a set.
 */

export const PALETTE: Record<string, string | null> = {
    '.': null, // transparent
    '0': '#171009', // deepest outline
    'K': '#2e2216', // outline
    'k': '#453422', // soft outline
    '1': '#1f4a1a', // deep foliage
    'G': '#2f6b24', // foliage dark
    'g': '#47912f', // foliage
    'h': '#63b241', // foliage light
    'p': '#8ad25f', // foliage highlight
    'P': '#b9e890', // foliage pale
    'n': '#3a2917', // dark earth
    'T': '#5c4126', // bark dark
    't': '#7d5a33', // bark
    'u': '#a37c48', // bark light
    's': '#96866a', // stone dark
    'S': '#c0ae8e', // stone
    'w': '#ded4bd', // stone light
    'W': '#f6efe2', // white
    'F': '#e6e0cf', // pale cloth
    'R': '#8f2c1f', // roof dark
    'r': '#c1432f', // roof
    'e': '#e2694b', // roof light
    'B': '#3f6fa8', // blue dark
    'b': '#5d93cc', // blue
    'c': '#8fbde8', // blue light
    'C': '#57a8d4', // water
    'Y': '#e8b53f', // gold
    'y': '#c1922c', // gold dark
    'O': '#d8813a', // orange
    'M': '#8f4f8c', // purple
    'm': '#c98cc4', // purple light
    'A': '#BFFF00', // the journal's glow
    'a': '#7fae00', // the glow, shaded
    'q': '#42301f', // spines, deep
    'Q': '#5e4430', // spines
    'j': '#7d5c3f', // spines, lit
    'x': '#c2905f', // snout and shade
    'z': '#e5bc8b', // hog
    'Z': '#f4d9b4', // hog, lit
}

export type Sprite = string[]

/** Points the way out of town. */
export const SIGNPOST: Sprite = [
    '..................................',
    '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.',
    'KttttttttttttttttttttttttttttttttK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KtuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutK',
    'KttttttttttttttttttttttttttttttttK',
    '.KKKKKKKKKKKKKKKTtKKKKKKKKKKKKKKK.',
    '...............KTtK...............',
    '...............KTtK...............',
    '...............KTtK...............',
    '...............KTtK...............',
    '...............KTtK...............',
    '...............KTtK...............',
    '...............KTtK...............',
    '............KKKKTtKKKK............',
    '...........KTTTTTTTTTTK...........',
    '............KKKKKKKKKK............',
    '..................................',
]

/** You. The one in the bright green cap. */
export const HERO_A: Sprite = [
    '................................',
    '..........qqAAAAAAAA............',
    '.......qqQAAAAAAAAAAAAq.........',
    '.....qqQQAAAAAAAAAAAAAAQq.......',
    '....qQQQKaaaaaaaaaaaaaaKQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......qQQQQQQQQQQQQQQQq.........',
    '.......KKzzzzzzzzzzzzKK.........',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '.......KKxxxK....KxxxKK.........',
    '........KKKK......KKKK..........',
]

export const HERO_B: Sprite = [
    '................................',
    '..........qqAAAAAAAA............',
    '.......qqQAAAAAAAAAAAAq.........',
    '.....qqQQAAAAAAAAAAAAAAQq.......',
    '....qQQQKaaaaaaaaaaaaaaKQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......qQQQQQQQQQQQQQQQq.........',
    '.......KKzzzzzzzzzzzzKK.........',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '......KxxxK........KxxxK........',
    '.....KKxxxKK......KKxxxKK.......',
    '.....KKKKKK........KKKKKK.......',
]

/** Pell, who has walked the harbour road for forty years. */
export const PELL_A: Sprite = [
    '................................',
    '..........qqWWWWWWWW............',
    '.......qqQWWWWWWWWWWWWq.........',
    '.....qqQQWWWWWWWWWWWWWWQq.......',
    '....qQQQKBBBBBBBBBBBBBBKQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......qQQQQQQQQQQQQQQQq.........',
    '.......KKzzzzzzzzzzzzKK.........',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '.......KKxxxK....KxxxKK.........',
    '........KKKK......KKKK..........',
]

export const PELL_B: Sprite = [
    '................................',
    '..........qqWWWWWWWW............',
    '.......qqQWWWWWWWWWWWWq.........',
    '.....qqQQWWWWWWWWWWWWWWQq.......',
    '....qQQQKBBBBBBBBBBBBBBKQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......qQQQQQQQQQQQQQQQq.........',
    '.......KKzzzzzzzzzzzzKK.........',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '......KxxxK........KxxxK........',
    '.....KKxxxKK......KKxxxKK.......',
    '.....KKKKKK........KKKKKK.......',
]

/** Marn, who keeps the inn and never uses one word where nine will do. */
export const MARN_A: Sprite = [
    '................................',
    '..........qqqqqqqqqq............',
    '.......qqQQQQQQQQQQQQqq.........',
    '.....qqQQQQQQQQQQQQQQQQQq.......',
    '....qQQQjjQQQQjjQQQQjjQQQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......OOOOOOOOOOOOOOOOOOOO......',
    '......OOOOOOOOOOOOOOOOOOOO......',
    '.....KKzOOOOOOzzzzOOOOOOK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '.......KKxxxK....KxxxKK.........',
    '........KKKK......KKKK..........',
]

export const MARN_B: Sprite = [
    '................................',
    '..........qqqqqqqqqq............',
    '.......qqQQQQQQQQQQQQqq.........',
    '.....qqQQQQQQQQQQQQQQQQQq.......',
    '....qQQQjjQQQQjjQQQQjjQQQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......OOOOOOOOOOOOOOOOOOOO......',
    '......OOOOOOOOOOOOOOOOOOOO......',
    '.....KKzOOOOOOzzzzOOOOOOK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '......KxxxK........KxxxK........',
    '.....KKxxxKK......KKxxxKK.......',
    '.....KKKKKK........KKKKKK.......',
]

/** Kip, who is nine and certain about everything. */
export const KIP_A: Sprite = [
    '................................',
    '..........qqrrrrrrrr............',
    '.......qqQrrrrrrrrrrrrq.........',
    '.....qqQQrrrrrrrrrrrrrrQq.......',
    '....qQQQKRRRRRRRRRRRRRRKQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......qQQQQQQQQQQQQQQQq.........',
    '.......KKzzzzzzzzzzzzKK.........',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '.......KKxxxK....KxxxKK.........',
    '........KKKK......KKKK..........',
]

export const KIP_B: Sprite = [
    '................................',
    '..........qqrrrrrrrr............',
    '.......qqQrrrrrrrrrrrrq.........',
    '.....qqQQrrrrrrrrrrrrrrQq.......',
    '....qQQQKRRRRRRRRRRRRRRKQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '.qQQQQQKZZKKZZZZKKZZKQQQjjQQq...',
    '.qQQjjQKZZKKZZZZKKZZKQQQQQQQq...',
    '.qQQQQQKZZZZZZZZZZZZKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......qQQQQQQQQQQQQQQQq.........',
    '.......KKzzzzzzzzzzzzKK.........',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '......KxxxK........KxxxK........',
    '.....KKxxxKK......KKxxxKK.......',
    '.....KKKKKK........KKKKKK.......',
]

/** Row, who keeps the ledgers and says when she does not know. */
export const ROW_A: Sprite = [
    '................................',
    '..........qqqqqqqqqq............',
    '.......qqQQQQQQQQQQQQqq.........',
    '.....qqQQQQQQQQQQQQQQQQQq.......',
    '....qQQQjjQQQQjjQQQQjjQQQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZKKKKZZZKKKKQQQQQQQq...',
    '.qQQQQQKZKWWWWKZKWWWWKQQjjQQq...',
    '.qQQjjQKZKWWWWKZKWWWWKQQQQQQq...',
    '.qQQQQQKZZKKKKZZZKKKKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......MMMMMMMMMMMMMMMMMMMM......',
    '......MMMMMMMMMMMMMMMMMMMM......',
    '.....KKzMMMMMMzzzzMMMMMMK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '.......KKxxxK....KxxxKK.........',
    '........KKKK......KKKK..........',
]

export const ROW_B: Sprite = [
    '................................',
    '..........qqqqqqqqqq............',
    '.......qqQQQQQQQQQQQQqq.........',
    '.....qqQQQQQQQQQQQQQQQQQq.......',
    '....qQQQjjQQQQjjQQQQjjQQQq......',
    '...qQQQQQQQQQQQQQQQQQQQQQQq.....',
    '..qQQjjQQQQjjQQQQjjQQQQjjQQq....',
    '..qQQQQQQQQQQQQQQQQQQQQQQQQq....',
    '.qQQQQjjQQQQQQQQQQQQjjQQQQQQq...',
    '.qQQQQQQQKKKKKKKKKKQQQQQQQQQq...',
    '.qQQjjQQKZZZZZZZZZZKQQjjQQQQq...',
    '.qQQQQQKZZKKKKZZZKKKKQQQQQQQq...',
    '.qQQQQQKZKWWWWKZKWWWWKQQjjQQq...',
    '.qQQjjQKZKWWWWKZKWWWWKQQQQQQq...',
    '.qQQQQQKZZKKKKZZZKKKKQQQQQQQq...',
    '..qQQQQKZZZZxxxxZZZZKQQQQQQq....',
    '..qQQQQKZZZKxxxxKZZZKQQjjQQq....',
    '...qQQQKZZZZZZZZZZZZKQQQQQq.....',
    '....qQQQKZZZZZZZZZZKQQQQQq......',
    '.....qQQQKKKKKKKKKKQQQQQq.......',
    '......MMMMMMMMMMMMMMMMMMMM......',
    '......MMMMMMMMMMMMMMMMMMMM......',
    '.....KKzMMMMMMzzzzMMMMMMK.......',
    '....KzzzzzzzzzzzzzzzzzzzzK......',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzxzzzzzzzzzzzzzzzzzzzK.....',
    '...KzzzzzzzzzzzzzzzzzzzzzzK.....',
    '.....KKzzzzzzzzzzzzzzzzKK.......',
    '......KxxxK........KxxxK........',
    '.....KKxxxKK......KKxxxKK.......',
    '.....KKKKKK........KKKKKK.......',
]
