/**
 * Hand-authored pixel art. Each sprite is a list of equal-length rows mapped
 * through PALETTE. No external assets, so nothing to license or load.
 * `pnpm validate:sprites` checks every row length and character.
 *
 * Characters are 24x24. Scenery varies.
 */

export const PALETTE: Record<string, string | null> = {
    '.': null,
    k: '#1d1710',
    K: '#332618',
    G: '#3f7a2e',
    g: '#5fa83c',
    h: '#8ed15a',
    T: '#6b4a2a',
    t: '#8a6238',
    n: '#4a3320',
    W: '#f7efe0',
    S: '#cdbb9c',
    s: '#9b8a70',
    A: '#BFFF00',
    a: '#7fae00',
    Y: '#f2c14e',
    y: '#d9a441',
    R: '#d1452f',
    B: '#4f7fb8',
    b: '#7fb0dd',
    O: '#e08a3c',
    F: '#e4dfd0',
    M: '#c46bb0',
    P: '#a8d85f',
}

export type Sprite = string[]

/* ---------- you ---------- */

export const HERO_A: Sprite = [
    '........................',
    '...........AA...........',
    '..........AAAA..........',
    '.........AAAAAA.........',
    '........AAAAAAAA........',
    '.......AAAAAAAAAA.......',
    '......AAAAAAAAAAAA......',
    '.....KKKKKKKKKKKKKK.....',
    '........KWWWWWWK........',
    '.......KWWWWWWWWK.......',
    '.......KWkWWWWkWK.......',
    '.......KWWWWWWWWK.......',
    '.......KWWWkkWWWK.......',
    '........KWWWWWWK........',
    '.........KWWWWK.........',
    '......KKKKBBBBKKKK......',
    '.....KBBBBBBBBBBBBK.....',
    '....KBBBBBBBBBBBBBBK....',
    '....KBWBBBBBBBBBBWBK....',
    '....KBBBBBBBBBBBBBBK....',
    '.....KBBBBBBBBBBBBK.....',
    '......KBBBBBBBBBBK......',
    '......KTTKK..KKTTK......',
    '.......KKK....KKK.......',
]

export const HERO_B: Sprite = [
    '........................',
    '...........AA...........',
    '..........AAAA..........',
    '.........AAAAAA.........',
    '........AAAAAAAA........',
    '.......AAAAAAAAAA.......',
    '......AAAAAAAAAAAA......',
    '.....KKKKKKKKKKKKKK.....',
    '........KWWWWWWK........',
    '.......KWWWWWWWWK.......',
    '.......KWkWWWWkWK.......',
    '.......KWWWWWWWWK.......',
    '.......KWWWkkWWWK.......',
    '........KWWWWWWK........',
    '.........KWWWWK.........',
    '......KKKKBBBBKKKK......',
    '.....KBBBBBBBBBBBBK.....',
    '....KBBBBBBBBBBBBBBK....',
    '....KBWBBBBBBBBBBWBK....',
    '....KBBBBBBBBBBBBBBK....',
    '.....KBBBBBBBBBBBBK.....',
    '......KBBBBBBBBBBK......',
    '.....KTTKK....KKTTK.....',
    '.....KKK........KKK.....',
]

/* ---------- villagers ---------- */

export const VILLAGER_A: Sprite = [
    '........................',
    '........................',
    '......YYYYYYYYYYYY......',
    '....YYYYYYYYYYYYYYYY....',
    '..YYYYYYYYYYYYYYYYYYYY..',
    '....KKKKKKKKKKKKKKKK....',
    '........KWWWWWWK........',
    '.......KWWWWWWWWK.......',
    '.......KWkWWWWkWK.......',
    '.......KWWWWWWWWK.......',
    '.......KWWWkkWWWK.......',
    '........KWWWWWWK........',
    '.........KWWWWK.........',
    '......KKKKOOOOKKKK......',
    '.....KOOOOOOOOOOOOK.....',
    '....KOOOOOOOOOOOOOOK....',
    '....KOWOOOOOOOOOOWOK....',
    '....KOOOOOOOOOOOOOOK....',
    '.....KOOOOOOOOOOOOK.....',
    '......KOOOOOOOOOOK......',
    '......KOOOOOOOOOOK......',
    '......KnnKK..KKnnK......',
    '.......KKK....KKK.......',
    '........................',
]

export const VILLAGER_B: Sprite = [
    '........................',
    '........................',
    '........................',
    '......YYYYYYYYYYYY......',
    '....YYYYYYYYYYYYYYYY....',
    '..YYYYYYYYYYYYYYYYYYYY..',
    '....KKKKKKKKKKKKKKKK....',
    '........KWWWWWWK........',
    '.......KWWWWWWWWK.......',
    '.......KWkWWWWkWK.......',
    '.......KWWWWWWWWK.......',
    '.......KWWWkkWWWK.......',
    '........KWWWWWWK........',
    '.........KWWWWK.........',
    '......KKKKOOOOKKKK......',
    '.....KOOOOOOOOOOOOK.....',
    '....KOOOOOOOOOOOOOOK....',
    '....KOWOOOOOOOOOOWOK....',
    '....KOOOOOOOOOOOOOOK....',
    '.....KOOOOOOOOOOOOK.....',
    '......KOOOOOOOOOOK......',
    '......KnnKK..KKnnK......',
    '.......KKK....KKK.......',
    '........................',
]

/** The old woman who gives you the lantern. */
export const ELDER_A: Sprite = [
    '........................',
    '........................',
    '........KKKKKKKK........',
    '.......KFFFFFFFFK.......',
    '......KFFFFFFFFFFK......',
    '......KFWWWWWWWWFK......',
    '......KFWkWWWWkWFK......',
    '.......KWWWWWWWWK.......',
    '.......KWWWkkWWWK.......',
    '........KWWWWWWK........',
    '.........KWWWWK.........',
    '......KKKKMMMMKKKK......',
    '.....KMMMMMMMMMMMMK.....',
    '....KMMMMMMMMMMMMMMK....',
    '....KMWMMMMMMMMMMWMK....',
    '....KMMMMMMMMMMMMMMK..A.',
    '.....KMMMMMMMMMMMMK.AAA.',
    '......KMMMMMMMMMMK..AAA.',
    '......KMMMMMMMMMMK...A..',
    '......KMMMMMMMMMMK...T..',
    '......KnnKK..KKnnK...T..',
    '.......KKK....KKK....T..',
    '........................',
    '........................',
]

export const ELDER_B: Sprite = [
    '........................',
    '........................',
    '........................',
    '........KKKKKKKK........',
    '.......KFFFFFFFFK.......',
    '......KFFFFFFFFFFK......',
    '......KFWWWWWWWWFK......',
    '......KFWkWWWWkWFK......',
    '.......KWWWWWWWWK.......',
    '.......KWWWkkWWWK.......',
    '........KWWWWWWK........',
    '.........KWWWWK.........',
    '......KKKKMMMMKKKK......',
    '.....KMMMMMMMMMMMMK.....',
    '....KMMMMMMMMMMMMMMK....',
    '....KMWMMMMMMMMMMWMK..A.',
    '....KMMMMMMMMMMMMMMK.AAA',
    '.....KMMMMMMMMMMMMK..AAA',
    '......KMMMMMMMMMMK....A.',
    '......KMMMMMMMMMMK....T.',
    '......KnnKK..KKnnK....T.',
    '.......KKK....KKK.....T.',
    '........................',
    '........................',
]

/* ---------- the four helpers ---------- */

/** Finder: a mole in spectacles, holding a page from the village book. */
export const FINDER: Sprite = [
    '........................',
    '........................',
    '.......KKKKKKKKKK.......',
    '.....KKTTTTTTTTTTKK.....',
    '....KTTTTTTTTTTTTTTK....',
    '....KTTKKTTTTTTKKTTK....',
    '....KTKWWKTTTTKWWKTK....',
    '....KTKWkWKTTKWkWKTK....',
    '....KTKWWWKTTKWWWKTK....',
    '....KTTKKTTTTTTKKTTK....',
    '.....KTTTTTMMTTTTTK.....',
    '......KTTTTMMTTTTK......',
    '.......KTTTTTTTTK.......',
    '....KKKKTTTTTTTTKKKK....',
    '...KTTTTTTTTTTTTTTTTK...',
    '...KTTKWWWWWWWWWWKTTK...',
    '...KTTKWSSSSSSSSWKTTK...',
    '...KTTKWSSSSSSSSWKTTK...',
    '...KTTKWWWWWWWWWWKTTK...',
    '...KTTTTTTTTTTTTTTTTK...',
    '....KTTTTTTTTTTTTTTK....',
    '.....KttKK....KKttK.....',
    '......KKK......KKK......',
    '........................',
]

/** Thinker: an owl on a stump. */
export const THINKER: Sprite = [
    '........................',
    '.......KK......KK.......',
    '......KttK....KttK......',
    '.....KtttKKKKKKtttK.....',
    '....KttttttttttttttK....',
    '....KtttttttttttttttK...',
    '...KttKWWWWKKWWWWKttK...',
    '...KtKWWWWWWWWWWWWKtK...',
    '...KtKWWkkWWWWkkWWKtK...',
    '...KtKWWkkWWWWkkWWKtK...',
    '...KtKWWWWWYYWWWWWKtK...',
    '...KtKWWWWWYYWWWWWKtK...',
    '...KttKWWWWWWWWWWKttK...',
    '....KttttttttttttttK....',
    '....KtTTtTTtTTtTTtTK....',
    '.....KtTTtTTtTTtTTK.....',
    '......KttTTtTTttK.......',
    '.......KKYYKKYYKK.......',
    '........KYYKKYYK........',
    '.......KKKKKKKKKK.......',
    '......KTTTTTTTTTTK......',
    '.....KTTTTTTTTTTTTK.....',
    '.....KKKKKKKKKKKKKK.....',
    '........................',
]

/** Runner: a rabbit with a satchel. */
export const RUNNER: Sprite = [
    '........................',
    '......KK........KK......',
    '.....KSSK......KSSK.....',
    '.....KSMSK....KSMSK.....',
    '.....KSMSK....KSMSK.....',
    '.....KSMSK....KSMSK.....',
    '.....KSSSKKKKKKSSSK.....',
    '......KSSSSSSSSSSK......',
    '.....KSSSSSSSSSSSSK.....',
    '....KSSKWWKSSKWWKSSK....',
    '....KSSKWkKSSKWkKSSK....',
    '....KSSSSSSMMSSSSSSK....',
    '....KSSSSSSMMSSSSSSK....',
    '.....KSSSSSSSSSSSSK.....',
    '......KSSSSSSSSSSK......',
    '.....KSSSSSSSSSSSSK.....',
    '....KSSKTTTTTTTTKSSK....',
    '....KSSKTTyyyyTTKSSK....',
    '....KSSKTTTTTTTTKSSK....',
    '.....KSSSSSSSSSSSSK.....',
    '......KSSSSSSSSSSK......',
    '......KSSKK..KKSSK......',
    '.......KKK....KKK.......',
    '........................',
]

/** Teller: a carved stone face on a post. */
export const TELLER: Sprite = [
    '........................',
    '......KKKKKKKKKKKK......',
    '....KKSSSSSSSSSSSSKK....',
    '...KSSSSSSSSSSSSSSSSK...',
    '..KSSSSSSSSSSSSSSSSSSK..',
    '..KSSKKSSSSSSSSSSKKSSK..',
    '..KSSKAAKSSSSSSKAAKSSK..',
    '..KSSKAAKSSSSSSKAAKSSK..',
    '..KSSKKSSSSSSSSSSKKSSK..',
    '..KSSSSSSSSSSSSSSSSSSK..',
    '..KSSSSSSKAAAAKSSSSSSK..',
    '..KSSSSSKAAAAAAKSSSSSK..',
    '..KSSSSSSKAAAAKSSSSSSK..',
    '...KSSSSSSSSSSSSSSSSK...',
    '....KSSSSSSSSSSSSSSK....',
    '.....KKSSSSSSSSSSKK.....',
    '.......KKKKKKKKKK.......',
    '.........KssssK.........',
    '.........KssssK.........',
    '.........KssssK.........',
    '.......KKssssssKK.......',
    '......KSSSSSSSSSSK......',
    '......KKKKKKKKKKKK......',
    '........................',
]

/** What a helper looks like before you carry the lantern. */
export const FOG_A: Sprite = [
    '........................',
    '.........FFFFFF.........',
    '.......FFFFFFFFFF.......',
    '.....FFFFFFFFFFFFFF.....',
    '....FFFFFFFFFFFFFFFF....',
    '...FFFFFFFFFFFFFFFFFF...',
    '..FFFFFFFFFFFFFFFFFFFF..',
    '..FFFFFFFFFFFFFFFFFFFF..',
    '.FFFFFFFFFFFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFFFFFFFFFFF.',
    '.FFFFFFFFFFFFFFFFFFFFFF.',
    '..FFFFFFFFFFFFFFFFFFFF..',
    '..FFFFFFFFFFFFFFFFFFFF..',
    '...FFFFFFFFFFFFFFFFFF...',
    '....FFFFFFFFFFFFFFFF....',
    '.....FFFFFFFFFFFFFF.....',
    '.......FFFFFFFFFF.......',
    '.........FFFFFF.........',
    '........................',
    '........................',
    '........................',
]

export const FOG_B: Sprite = [
    '........................',
    '........FFFFFF..........',
    '......FFFFFFFFFF........',
    '....FFFFFFFFFFFFFF......',
    '...FFFFFFFFFFFFFFFF.....',
    '..FFFFFFFFFFFFFFFFFF....',
    '.FFFFFFFFFFFFFFFFFFFF...',
    '.FFFFFFFFFFFFFFFFFFFF...',
    'FFFFFFFFFFFFFFFFFFFFFF..',
    'FFFFFFFFFFFFFFFFFFFFFF..',
    'FFFFFFFFFFFFFFFFFFFFFF..',
    'FFFFFFFFFFFFFFFFFFFFFF..',
    'FFFFFFFFFFFFFFFFFFFFFF..',
    'FFFFFFFFFFFFFFFFFFFFFF..',
    '.FFFFFFFFFFFFFFFFFFFF...',
    '.FFFFFFFFFFFFFFFFFFFF...',
    '..FFFFFFFFFFFFFFFFFF....',
    '...FFFFFFFFFFFFFFFF.....',
    '....FFFFFFFFFFFFFF......',
    '......FFFFFFFFFF........',
    '........FFFFFF..........',
    '........................',
    '........................',
    '........................',
]

/** The stone you ask the Oracle from. */
export const PLINTH: Sprite = [
    '........................',
    '..........AA............',
    '.........AAAA...........',
    '..........AA............',
    '........................',
    '.......KKSSSSKK.........',
    '......KSSSSSSSSK........',
    '.....KSSSSSSSSSSK.......',
    '.....KSSSKAAKSSSK.......',
    '.....KSSSKAAKSSSK.......',
    '.....KSSSSSSSSSSK.......',
    '.....KSSSSSSSSSSK.......',
    '.....KSSsSSSSsSSK.......',
    '.....KSSSSSSSSSSK.......',
    '....KSSSSSSSSSSSSK......',
    '....KSSSSSSSSSSSSK......',
    '...KSSSSSSSSSSSSSSK.....',
    '...KSSSSSSSSSSSSSSK.....',
    '..KSSSSSSSSSSSSSSSSK....',
    '..KssssssssssssssssK....',
    '..KKKKKKKKKKKKKKKKKK....',
    '........................',
    '........................',
    '........................',
]

/* ---------- scenery ---------- */

export const TREE: Sprite = [
    '........GGGGGGGG........',
    '......GGhhhhhhhhGG......',
    '....GGhhhhhhhhhhhhGG....',
    '...GhhhhhhhhhhhhhhhhG...',
    '..GhhhhhghhhhhghhhhhhG..',
    '..GhhhhhhhhhhhhhhhhhhG..',
    '.GhhhhhhhhPhhhhhhhhhhhG.',
    '.GhhhghhhhhhhhhghhhhhhG.',
    '.GhhhhhhhhhhhhhhhhhhhhG.',
    '..GhhhhhhhhhhhhhhhhhhG..',
    '..GhhhhhghhhhhghhhhhhG..',
    '...GhhhhhhhhhhhhhhhhG...',
    '....GGhhhhhhhhhhhhGG....',
    '......GGhhhhhhhhGG......',
    '........GGGGGGGG........',
    '..........TTt...........',
    '..........TTt...........',
    '..........TTt...........',
    '..........TTt...........',
    '.........TTTtt..........',
    '.........TTTtt..........',
    '........TTTTttt.........',
    '.......TTTTTtttt........',
    '......KKKKKKKKKKK.......',
]

export const BUSH: Sprite = [
    '........................',
    '........................',
    '.........GGGGG..........',
    '.......GGhhhhhGG........',
    '.....GGhhhhhhhhhGG......',
    '....GhhhhhMhhhhhhhG.....',
    '...GhhhhhhhhhhhhhhhG....',
    '...GhhhhhhhhhhMhhhhG....',
    '...GghhhhhhhhhhhhhgG....',
    '...KGgggggggggggggGK....',
    '....KGGGGGGGGGGGGGK.....',
    '......KKKKKKKKKKK.......',
    '........................',
    '........................',
    '........................',
    '........................',
]

export const FLOWERS: Sprite = [
    '........................',
    '........................',
    '........................',
    '...M.......Y.......M....',
    '..MMM.....YYY.....MMM...',
    '.MMMMM...YYYYY...MMMMM..',
    '..MMM.....YYY.....MMM...',
    '...M.......Y.......M....',
    '...g.......g.......g....',
    '...g.......g.......g....',
    '..ggg.....ggg.....ggg...',
    '.GgggG...GgggG...GgggG..',
    '........................',
    '........................',
    '........................',
    '........................',
]

export const MUSHROOMS: Sprite = [
    '........................',
    '........................',
    '........................',
    '.....RRRR...............',
    '...RRRRRRRR.....RRRR....',
    '..RRRWRRRWRR..RRRRRRRR..',
    '..RRRRRRRRRR..RRRWRRRR..',
    '...RRRRRRRR...RRRRRRRR..',
    '.....WWWW......RRRRRR...',
    '.....WWWW........WWW....',
    '.....WWWW........WWW....',
    '....KWWWWK......KWWWK...',
    '........................',
    '........................',
    '........................',
    '........................',
]

export const ROCK: Sprite = [
    '........................',
    '........................',
    '........................',
    '.........KKKKKK.........',
    '.......KKSSSSSSKK.......',
    '.....KKSSSSSSSSSSKK.....',
    '....KSSSSSSSSSSSSSSK....',
    '....KSSSSSSSSSSSSSSK....',
    '....KSSSSSSSSSSSSSSK....',
    '....KssssssssssssssK....',
    '....KKKKKKKKKKKKKKKK....',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
]

/** A patch of the crop the first villager is worried about. */
export const POTATOES: Sprite = [
    '........................',
    '........................',
    '........................',
    '....hh....hh....hh......',
    '...hGGh..hGGh..hGGh.....',
    '..hGGGGh.hGGGGh.hGGGGh..',
    '...hGGh..hGGh..hGGh.....',
    '....hh....hh....hh......',
    '..TTTTTTTTTTTTTTTTTTTT..',
    '.TTTTTTTTTTTTTTTTTTTTTT.',
    '.TTnTTTTnTTTTnTTTTnTTTT.',
    '.TTTTTTTTTTTTTTTTTTTTTT.',
    '..TTTTTTTTTTTTTTTTTTTT..',
    '........................',
    '........................',
    '........................',
]

/** Grows in front of Teller as it demands more of the book be read out. */
export const BOOK_PILE: Sprite = [
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '........................',
    '.....KWWWWK.KWWWWK......',
    '.....KWSSWK.KWSSWK......',
    '.....KWWWWK.KWWWWK......',
    '...KWWWWWWWWWWWWWWK.....',
    '...KWSSSSSSSSSSSSWK.....',
    '...KWWWWWWWWWWWWWWK.....',
    '..KWWWWWWWWWWWWWWWWK....',
    '..KWSSSSSSSSSSSSSSWK....',
    '..KWWWWWWWWWWWWWWWWK....',
    '..KKKKKKKKKKKKKKKKKK....',
]
